language: generic
dist: trusty
matrix:
  include:
    - os: linux
      env: TEST_SUITE=quarkc
#    - os: linux
#      env: TEST_SUITE=runtime
#    - os: linux
#      env: TEST_SUITE=examples
    - os: osx
      env: TEST_SUITE=examples
  exclude:
    - env: TEST_SUITE=should-never-be-selected

sudo: required
env:
  matrix:
    - TEST_SUITE=should-never-be-selected
  global:
  - secure: Ht+kRWkOtZl6i0RmWaKc4OJj2m4JG8ugWzweilaCH5xfxUEUeRhTvFSZNWeA1ZNxWmgSdS27HxAfdzDiZcp8lkZdLbeFBjcWIlFHVjB71hXV5ZV88v59TDZPcmULAFwp2SdZ5ZVjKU471CeBdVFhWupjSIxTfyULMk6/70vpLthioVMEGEUDtY190fNXr5NaBfEnIJ5+/XbVLnBC4knNQ6vjjO1I/KmJvjtpj7h2pBJDfK54fXL3I7x4N90tEOmU3mIJm1YoQO6CexOyz3CdlJRUvSPZVBF5Y0qDd3tPVqDE7F1DH+JSz7SJOn5HHASFFK0BXpscwSwskmGmiNSOEbWLHiFojCszs3GHUx/Lv9/bKRl6NbsZkcFfMzPnqXIg7+HQcaqF/wW7TN5rDmp1H9m2o0sD93Spk5gW9a/d4sUrRS1D+B4HPN9kZoBeKPah0gM6QelKOaLxZvQYcY4gJZOFHi+JPVGeomVpWVXPYuKrYbrCtzuDth1UdmslO6kM7s3joQKnSX2At5VekpAJd4eKNjojunwxHssUWjcQixkul3Wd2i0ap4yzDNsPo9I1KreMnopxANqPJCeIWW+PZ1uO5hNAFSML45fmlNcct7h/qLfSzazeujcPW7zwW4YhPxZFYAWdAwlD3/VrEI4JbVQQN0xkfmeyNQpXYIMl9Ak=
  - secure: uRBpgYiXx9vBF/DEJsYJpqOthWCwbPsz3gSaVOpojfvvTA83MeBokjIIMAfyTO7oJxU73j6utVLZnuo86R8vPpH80pRmt0zgf0DtoC9eosytbd6HKab0iQPVOhQMnR/w03xi+LM6RBc/DPN4OjpQQPUKuYa1BUsgutXHedvEAVif3m4u+7zNrZEt3vP+/WZ+gQhnZnQjFcPJR7Z5eon2/ZRX0jF9JDZxsAR2aRsplAg1HQE5/0hsL5ZHLnFwt8/D6nDDFHO30Z49mZNCxCJj8xzIb0iSab8/WgAPz/xYgWTnz7k41po+8mkIy5EhDdB2nLyrMzQNNVaJPp90GUQqS3I29g+Tjmfzx0vNdU5k4+v51EUfltLw0J0OivBDOPdijKOQTlKOWL10ZhRsdqRagBo/M0VDG/B7JkFfB2hT/X2UKLCtmKOeWinvInOXPQsdPlWkRxf+E65gqwZ4qEojNxvAj7qANg7TT/LhmGsFTzQyGAm9rSU7gsniNsAzlDoCkG75aWnz3ZPZkcpd8U2AaiSx9oHesYiK6x+UDS1rBcarsIL1yaawANZd68KOEriR44eXilFsOUmN7zYH+JkXEsx1zUP5PTUPmrKavuBuP1WYL5qaUithgX7p8JD2285eCdSZuDPTbbq1/ypGHU7s6OhoNX0mGm2X/N/yVudxK2w=

before_install:
- openssl aes-256-cbc -K $encrypted_cdfbaa8bcf7f_key -iv $encrypted_cdfbaa8bcf7f_iv
  -in .respawn.token.enc -out .respawn.token -d

install:
- .travis/install.sh

script:
- .travis/test.sh
- .travis/deploy.sh

notifications:
  slack:
    rooms:
      secure: kK5qUpRLVg90qPYaW3rumkhz8uDeHhMmurWb5mwFQMoxP8oROTlazyXpSatBvdVBGB2PVF/zc3FWMK7EQ62Qs4JcfXhukxhnQYmAsSENJVdnQJQXAtJZamtobmE9D7F/rbCXaxpY1sXGoMXRcYlwyU2bo0CneDve0Kh0cFlr700oBUvcSx/xhF/+6Prb0BLvqiq5kpLsZSsWkI4UAuxhDCRWOLmgATNcsPKdBfROmWO4GJ2yHx1USdIlm9ibaDS+I2gv2zJIpOttCAEYNbL/oYDHx7gZdmaIBui/Fq44RDGjcnrB0zdCasGUZs9VM+6AfjXmbUvCrkU3G5+htSreS6wyMtwSr/K/+DPvbzq4di1HullcxgP+jC7UTXHLjuejh9oxxIp7azDq9P/QjMKqZ4VyiF3MUKwGhok4DqMi35HQoXtqWoWf5BgvIa8EylUFBXSPKWEw5MhtPyzq8wD1/HfvJQzmZqovSab9HsNQr8ATzlXbg3DjlInEbeFgd0bjgQW+B/8/LvLUuBXVAqv5IgHSx/fMGl6Ol9cIwQUjyLBrvgtPMpqQtHIIw1qS88q+iR/AP0XhS44eUORkw8Bm0FVlD7qR4qDQFAreO143kbDJ3f+chriSp/LcgyxxmShLIZcpg1yli2zOFIY4ZF0qoVpOOzNc6d28X2+6P6L+SM8=
    on_success: always
    on_failure: always
