os:
- linux
sudo: false
env:
  - TRAVIS_NODE_VERSION="4.2.2"
language:
- java
- python
python:
- 2.7
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - libssl-dev
    - swig
    - python-dev
    - curl
    - python-pip
    - tar
    - gcc
    - make
    - python-dev
    - libffi-dev
    - python-virtualenv

install:
- java -version 2>&1 | grep -Fe 'java version "1.8.0'
- python --version 2>&1 | grep -Fe 'Python 2.7'
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- nvm alias default $TRAVIS_NODE_VERSION
- node --version
- virtualenv quark-travis
- . quark-travis/bin/activate
- pip install --upgrade pip
- scripts/develop.sh

script:
- py.test -v quark
