language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      env: TEST_SUITE=quarkc
    - os: linux
      dist: trusty
      env: TEST_SUITE=runtime
    - os: linux
      dist: trusty
      env: TEST_SUITE=examples
    - os: osx
      env: TEST_SUITE=examples
  exclude:
    - env: TEST_SUITE=should-never-be-selected

sudo: required
env:
  matrix:
    - TEST_SUITE=should-never-be-selected
  global:
  - secure: Ht+kRWkOtZl6i0RmWaKc4OJj2m4JG8ugWzweilaCH5xfxUEUeRhTvFSZNWeA1ZNxWmgSdS27HxAfdzDiZcp8lkZdLbeFBjcWIlFHVjB71hXV5ZV88v59TDZPcmULAFwp2SdZ5ZVjKU471CeBdVFhWupjSIxTfyULMk6/70vpLthioVMEGEUDtY190fNXr5NaBfEnIJ5+/XbVLnBC4knNQ6vjjO1I/KmJvjtpj7h2pBJDfK54fXL3I7x4N90tEOmU3mIJm1YoQO6CexOyz3CdlJRUvSPZVBF5Y0qDd3tPVqDE7F1DH+JSz7SJOn5HHASFFK0BXpscwSwskmGmiNSOEbWLHiFojCszs3GHUx/Lv9/bKRl6NbsZkcFfMzPnqXIg7+HQcaqF/wW7TN5rDmp1H9m2o0sD93Spk5gW9a/d4sUrRS1D+B4HPN9kZoBeKPah0gM6QelKOaLxZvQYcY4gJZOFHi+JPVGeomVpWVXPYuKrYbrCtzuDth1UdmslO6kM7s3joQKnSX2At5VekpAJd4eKNjojunwxHssUWjcQixkul3Wd2i0ap4yzDNsPo9I1KreMnopxANqPJCeIWW+PZ1uO5hNAFSML45fmlNcct7h/qLfSzazeujcPW7zwW4YhPxZFYAWdAwlD3/VrEI4JbVQQN0xkfmeyNQpXYIMl9Ak=
  - QUARK_PACKAGE=.
  - STATE=ci-run
  - TESTPYPI=https://testpypi.python.org/pypi
  - REALPYPI=https://pypi.python.org/pypi
  - PYPI=$REALPYPI
  - DEPLOYMENT_TOKEN_FILE=.i.am.the.master

before_install:
- openssl aes-256-cbc -K $encrypted_cdfbaa8bcf7f_key -iv $encrypted_cdfbaa8bcf7f_iv
  -in .respawn.token.enc -out .respawn.token -d

# TODO: osx will require complete redo of install step, should move
# everything to a script but last pip install

install:
- scripts/travis-install.sh

script:
- . quark-travis/bin/activate
- py.test -v $TEST_SUITE --durations=10 --collect-only
- if $(npm bin)/travis-after-all ; then
    touch $DEPLOYMENT_TOKEN_FILE ;
    echo "Master in STATE=$STATE.";
  else
    rm -f $DEPLOYMENT_TOKEN_FILE;
    echo "Failure or Not Master in STATE=$STATE.";
  fi

# TODO: travis is way too fragile to handle any of the stuff below,
# move to shellscripts and call them at the end of script block inside
# travis-after-all

notifications:
  slack:
    rooms:
      secure: kK5qUpRLVg90qPYaW3rumkhz8uDeHhMmurWb5mwFQMoxP8oROTlazyXpSatBvdVBGB2PVF/zc3FWMK7EQ62Qs4JcfXhukxhnQYmAsSENJVdnQJQXAtJZamtobmE9D7F/rbCXaxpY1sXGoMXRcYlwyU2bo0CneDve0Kh0cFlr700oBUvcSx/xhF/+6Prb0BLvqiq5kpLsZSsWkI4UAuxhDCRWOLmgATNcsPKdBfROmWO4GJ2yHx1USdIlm9ibaDS+I2gv2zJIpOttCAEYNbL/oYDHx7gZdmaIBui/Fq44RDGjcnrB0zdCasGUZs9VM+6AfjXmbUvCrkU3G5+htSreS6wyMtwSr/K/+DPvbzq4di1HullcxgP+jC7UTXHLjuejh9oxxIp7azDq9P/QjMKqZ4VyiF3MUKwGhok4DqMi35HQoXtqWoWf5BgvIa8EylUFBXSPKWEw5MhtPyzq8wD1/HfvJQzmZqovSab9HsNQr8ATzlXbg3DjlInEbeFgd0bjgQW+B/8/LvLUuBXVAqv5IgHSx/fMGl6Ol9cIwQUjyLBrvgtPMpqQtHIIw1qS88q+iR/AP0XhS44eUORkw8Bm0FVlD7qR4qDQFAreO143kbDJ3f+chriSp/LcgyxxmShLIZcpg1yli2zOFIY4ZF0qoVpOOzNc6d28X2+6P6L+SM8=
    on_success: always
    on_failure: always
after_success:
- if [[ ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "validate-dev" ) ]] ; then
    echo TODO TAG with DEV-success;
  fi
after_failure:
- if [[ ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "validate-dev" ) ]] ; then
    echo TODO TAG with DEV-fail;
  fi
before_deploy:
- if [[ -f .before.deploy.flag ]] ; then
    echo "Duplicate before_deploy???";
  else
    touch .before.deploy.flag &&
    git remote set-branches --add origin master &&
    git fetch --unshallow &&
    scripts/compute-next-version;
  fi
deploy:
- provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: bozzo
  password:
    secure: edLNPe42PWFBVWvNb0i+cQBniI9LhWTvTE5l0eQs601iEy7L+OaY7CgaQUHCekQH23xYQiX78mLNUTJrl9+aMO0SoUX7iD7OhYj8wPIgNgoU6qp08zgJdFjMbecl+lDh0Z/eaVtjobWS3TBgFltY4GHQMrTGF+ZM2nuZdgy72ug1Pot4x0wzAw/Fwj/ROug4FalsgLsTTfpAVzUxmYTvk78HEp/0QkXZ/SMtJ0TViUwQsibahpkLltU6G2TlZqTGLZQpK3p2CJKmSbHmkQLZxxe1g9hs3W9ppHQdZC9IqN5Z2m7oDco+32R7bfwOkM2LqT7B6wm9KbhS32dgzsTCaSw4hFT5SMcZwQBGVopK+lCvwq7EOa0jz6ju7TpwJXyb804ddiBACpjW/xdyYjpl9eYt6Jl4EU4HEZSdfEmgbbT+F/Wrf8Ms1Fjl+V/1rEUThFxcDEfIeY327ftvaWZT8EMBSYIoXI4ZSWb3c5fyFcoRF3/OfTrEydno5T3niQVbYym0GCGN9bk5pqYbrpjFPWI2l+I69ljoazaXnpB9iSBXUoqWoyu2dLeZ9wSsnPwrpaV/ar+Ka6k5Y+ae8VSccQOjBgdUEbBPeTCdBBrVAYbHXxkpI+lms6Uys/meZIYC+PwnTuG8LqJ5rIi0ZEmq7QEMtfezkMkMgJnRa0BYIXw=
  skip_cleanup: true
  on:
    repo: datawire/quark
    branch: quarkdev-ci
    tags: false
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "ci-run" )

- provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: datawire
  password:
    secure: YJRQYpbeK3rWnKISEXM5EaUJAIilJ1ZyXwNWEgtpyilOG1FWwWLKYHDuJaBeqO7VsAqzCtDOomvXxkK5UT56wALEozPTg9HytC8A2/8rssIX4oru1lALWMuoPQgKu99oy46wgr1yGVmwN2Pjx3FebItj0111US3l0HEjTf4MDpWhnTl/yh8d7RU/KGzdYFcqIWnlk7ccQJ+uc65Cx0ZCLxjEJNi0RkAr34O0h/Nl6/gcr159WKDMz8Os3p0PSZzJywPA2XI9henHuJrInoNCp9XpK2VtuVNTmgnyz88y/kudifIkNLx5pcIZIHrH/LB2MYAyrzzfdiG7HNHq0NYomuTz5Z4rtXNXlbs8sOQxmg3iNnt9V/7H1vQSJNgVOouSyRN44SsKuYrGPhc2DtHcvf8xySkmiaDT7RtiLobY8mtTBTCpy3G3agBITth92trTL6+1ZYvoNjiU5i4PGv2xMgnwiOO8rPM5mkFapndZ+mh/KlG4hxNZOSAJSAi7M3OtH1hPZZGicqqJlGJSfV70C153wxLuR5vQ/EzFJF3zPjkTxaUMs1ih82mv6gBml7NEaPsREbXR/RqerqzohzbmrvUjIe7M++tZpqJ03pOI99UxuTxdUz3GvwTKWnuiLZ55IoOslgHm+dDDoH5B0TPQC0mDysftDlLy4ngEeHE7qxU=
  skip_cleanup: true
  on:
    repo: datawire/quark
    branch: quarkdev-ci
    tags: false
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "ci-run" ) && ( -f .PROVIDER.DISABLED.HACK )

# XXX: travis respawns oddly, replace with a commit on a ci-$next_version branch

- provider: script
  skip_cleanup: true
  on:
    repo: datawire/quark
    branch: quarkdev-ci
    tags: false
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "ci-run" )
  script: scripts/respawn.sh STATE=validate-dev PYPI="$TESTPYPI" QUARK_PACKAGE="datawire-quarkdev-bozzo"

# XXX: hack above, QUARK_PACKAGE should be datawire-quark==$next_version