language: generic
dist: trusty
sudo: false
group: beta

cache:
  directory:
  - $HOME/.quark/cache

install:
- gem install test-unit
- pip install --upgrade pip
- pip install --upgrade setuptools
- scripts/prepare-common.sh
- pip install .

script:
- .travis/test.sh

notifications:
  slack:
    rooms:
      secure: E67GlDOEiGoLHvvgmPOJD+B+JA5O9HNC29Hav5CzCCj5f22p4nLBB9p2rIj0wiJXXhe0EePtILRM4oNpWNKS+mbCREXZHQB/668sqoogaVx86vweR+8VOX/BmW2HBlbP3WyOIpxgWKTt7yNj/o+bBr0Ofplu0NDZIflp/QSRJyeL2Phnsx2vbS0XRhk0fp3eLO2O7zymcRMkr8JftbSTfCF6R1ckTjmJshqdEHBuo7DJfWjn47k0+DxP/tWeQCJkIcpNkAtBMLOlqJ73YokOQ5PQsrsDNU5RilLB+Dv5EcycWVDjOgJH9QpXoMcq7dChLZV/MkGegd3yb0ee8EZVPj4mdQpnO8RxWhgSKjLPdkIN3sqGc+31gomz+7Hijk66028BnQ2qsdSeBoEi+RVG7MBUln4lHOk9726Swof533oj+14oSqrO/P6Yzc7Z+9x2XfbeCGgAsiwjDpJXg7BMXVqoaLzqZkmhcL97+QWWpCii45krftWU4bH2An6eZY6fJenIuz7R3NABKkpY+nTCzcGJH12wrHYnJK9M7pe94c+Xek3VDw7qMb6W8P119L/voWUEB3Bf3mdrH0NoChi6PFJdDk1i3aKRO+XXQKYUBAWoQkMOLX0VxzViVLdbKgcxBex9E3++u9pp2Tr+rGMKyy9O7AixZDNV/EFsuMxe8mY=
    on_success: always
    on_failure: always
