os:
- linux
sudo: required
dist: trusty
env:
  matrix:
  - TEST_SUITE=quarkc
  - TEST_SUITE=runtime
  - TEST_SUITE=examples
  global:
  - secure: Ht+kRWkOtZl6i0RmWaKc4OJj2m4JG8ugWzweilaCH5xfxUEUeRhTvFSZNWeA1ZNxWmgSdS27HxAfdzDiZcp8lkZdLbeFBjcWIlFHVjB71hXV5ZV88v59TDZPcmULAFwp2SdZ5ZVjKU471CeBdVFhWupjSIxTfyULMk6/70vpLthioVMEGEUDtY190fNXr5NaBfEnIJ5+/XbVLnBC4knNQ6vjjO1I/KmJvjtpj7h2pBJDfK54fXL3I7x4N90tEOmU3mIJm1YoQO6CexOyz3CdlJRUvSPZVBF5Y0qDd3tPVqDE7F1DH+JSz7SJOn5HHASFFK0BXpscwSwskmGmiNSOEbWLHiFojCszs3GHUx/Lv9/bKRl6NbsZkcFfMzPnqXIg7+HQcaqF/wW7TN5rDmp1H9m2o0sD93Spk5gW9a/d4sUrRS1D+B4HPN9kZoBeKPah0gM6QelKOaLxZvQYcY4gJZOFHi+JPVGeomVpWVXPYuKrYbrCtzuDth1UdmslO6kM7s3joQKnSX2At5VekpAJd4eKNjojunwxHssUWjcQixkul3Wd2i0ap4yzDNsPo9I1KreMnopxANqPJCeIWW+PZ1uO5hNAFSML45fmlNcct7h/qLfSzazeujcPW7zwW4YhPxZFYAWdAwlD3/VrEI4JbVQQN0xkfmeyNQpXYIMl9Ak=
  - QUARK_PACKAGE=.
  - STATE=ci-run
  - PYPI=https://pypi.python.org/pypi
  - TESTPYPI=https://testpypi.python.org/pypi
  - DEPLOYMENT_TOKEN_FILE=.i.am.the.master

language:
- java

python:
- 2.7.6

jdk:
- oraclejdk7

rvm:
- 2.3.0

addons:
  apt:
    packages:
    - libssl-dev
    - swig
    - python-dev
    - curl
    - python2.7
    - python-pip
    - tar
    - gcc
    - make
    - python-dev
    - libffi-dev
    - python-virtualenv

before_install:
- openssl aes-256-cbc -K $encrypted_cdfbaa8bcf7f_key -iv $encrypted_cdfbaa8bcf7f_iv
  -in .respawn.token.enc -out .respawn.token -d

install:
- java -version
- java -version 2>&1 | grep -Fe 'java version "1.7.0'
- python -c 'import sys; print sys.version; sys.exit(int(sys.version_info[:3] < (2,7,6)))'
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install 4.2.2
- nvm alias default 4.2.2
- node --version
- virtualenv quark-travis
- ". quark-travis/bin/activate"
- pip install --upgrade pip
- command rvm install 2.3.0
- rvm --default use 2.3.0
- ruby --version
- scripts/prepare-common.sh
- mvn --version
- npm install --save-dev travis-after-all
- gem install travis-yaml
- pip install -i $PYPI $QUARK_PACKAGE
- pip freeze

script:
- py.test -v $TEST_SUITE --durations=10 --collect-only
- if $(npm bin)/travis-after-all ; then
    touch $DEPLOYMENT_TOKEN_FILE ;
    ls -l $DEPLOYMENT_TOKEN_FILE ;
  else
    rm -f $DEPLOYMENT_TOKEN_FILE;
    echo "not master or failure";
  fi
- echo "State: =$STATE="

notifications:
  slack:
    rooms:
      secure: kK5qUpRLVg90qPYaW3rumkhz8uDeHhMmurWb5mwFQMoxP8oROTlazyXpSatBvdVBGB2PVF/zc3FWMK7EQ62Qs4JcfXhukxhnQYmAsSENJVdnQJQXAtJZamtobmE9D7F/rbCXaxpY1sXGoMXRcYlwyU2bo0CneDve0Kh0cFlr700oBUvcSx/xhF/+6Prb0BLvqiq5kpLsZSsWkI4UAuxhDCRWOLmgATNcsPKdBfROmWO4GJ2yHx1USdIlm9ibaDS+I2gv2zJIpOttCAEYNbL/oYDHx7gZdmaIBui/Fq44RDGjcnrB0zdCasGUZs9VM+6AfjXmbUvCrkU3G5+htSreS6wyMtwSr/K/+DPvbzq4di1HullcxgP+jC7UTXHLjuejh9oxxIp7azDq9P/QjMKqZ4VyiF3MUKwGhok4DqMi35HQoXtqWoWf5BgvIa8EylUFBXSPKWEw5MhtPyzq8wD1/HfvJQzmZqovSab9HsNQr8ATzlXbg3DjlInEbeFgd0bjgQW+B/8/LvLUuBXVAqv5IgHSx/fMGl6Ol9cIwQUjyLBrvgtPMpqQtHIIw1qS88q+iR/AP0XhS44eUORkw8Bm0FVlD7qR4qDQFAreO143kbDJ3f+chriSp/LcgyxxmShLIZcpg1yli2zOFIY4ZF0qoVpOOzNc6d28X2+6P6L+SM8=
    on_success: always
    on_failure: always
after_success:
- if [[ ( -f $DEPLOYMENT_TOKEN_FILE ) && ( $STATE" = "validate-dev" ) ]] ; then
    echo TODO TAG with DEV-success;
  fi
after_failure:
- if [[ ( -f $DEPLOYMENT_TOKEN_FILE ) && ( $STATE" = "validate-dev" ) ]] ; then
    echo TODO TAG with DEV-fail;
  fi
before_deploy:
- git remote set-branches --add origin master
- git fetch --unshallow
- scripts/compute-next-version
deploy:
- provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: datawire
  password:
    secure: YJRQYpbeK3rWnKISEXM5EaUJAIilJ1ZyXwNWEgtpyilOG1FWwWLKYHDuJaBeqO7VsAqzCtDOomvXxkK5UT56wALEozPTg9HytC8A2/8rssIX4oru1lALWMuoPQgKu99oy46wgr1yGVmwN2Pjx3FebItj0111US3l0HEjTf4MDpWhnTl/yh8d7RU/KGzdYFcqIWnlk7ccQJ+uc65Cx0ZCLxjEJNi0RkAr34O0h/Nl6/gcr159WKDMz8Os3p0PSZzJywPA2XI9henHuJrInoNCp9XpK2VtuVNTmgnyz88y/kudifIkNLx5pcIZIHrH/LB2MYAyrzzfdiG7HNHq0NYomuTz5Z4rtXNXlbs8sOQxmg3iNnt9V/7H1vQSJNgVOouSyRN44SsKuYrGPhc2DtHcvf8xySkmiaDT7RtiLobY8mtTBTCpy3G3agBITth92trTL6+1ZYvoNjiU5i4PGv2xMgnwiOO8rPM5mkFapndZ+mh/KlG4hxNZOSAJSAi7M3OtH1hPZZGicqqJlGJSfV70C153wxLuR5vQ/EzFJF3zPjkTxaUMs1ih82mv6gBml7NEaPsREbXR/RqerqzohzbmrvUjIe7M++tZpqJ03pOI99UxuTxdUz3GvwTKWnuiLZ55IoOslgHm+dDDoH5B0TPQC0mDysftDlLy4ngEeHE7qxU=
  skip_cleanup: true
  on:
    repo: datawire/quark
    branch: quarkdev-ci
    tags: false
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "ci-run" )
- provider: script
  skip_cleanup: true
  on:
    repo: datawire/quark
    branch: quarkdev-ci
    tags: false
    condition: ( -f $DEPLOYMENT_TOKEN_FILE ) && ( "$STATE" = "ci-run" )
  script: scripts/respawn.sh STATE=validate-dev PYPI="$TEST" QUARK_PACKAGE="datawire-quarkdev"
